# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20170905_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='eshop.Product'),
        ),
    ]
