# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_auto_20170905_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalorder',
            name='product_orders',
        ),
        migrations.AddField(
            model_name='productorder',
            name='total_order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='eshop.TotalOrder'),
        ),
    ]
